### ISSUE TITLE
running the code

### ISSUE THREAD

**Issue by ghost** [johnmyleswhite/FileFind.jl#3]
I'm trying to get the code running- I've successfully gotten the code cloned using the Pkg.clone() command, but I've tried running find from both the REPL command line and through executing the 01.jl example program provided, but I'm unable to get either one to run.

what is the correct syntax to run the function from the REPL command line?

**Comment by ghost** [comment]
My mistake- I had been assuming the 01.jl script was an executable script instead of usage examples.

**Comment by johnmyleswhite** [comment]
Glad you figured it out.
